/*
 * Copyright (C) 2015 - 2018 Intel Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __IA_CSS_ISA_PARAMETER_DEFS_DEP_H
#define __IA_CSS_ISA_PARAMETER_DEFS_DEP_H

/* ==================== DPC_V2 specific properties ==================== */
#define IA_CSS_ISA_KERNEL_IS_PRIMARY_DPC_V2			(1)
#define IA_CSS_ISA_NEEDS_SPATIAL_IN_DPC_V2			(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_OUT_DPC_V2			(0)
#define IA_CSS_ISA_NEEDS_SLICED_IN_DPC_V2			(1)
#define IA_CSS_ISA_NEEDS_SLICED_OUT_DPC_V2			(1)

/* ==================== CNL specific properties ==================== */
#define IA_CSS_ISA_KERNEL_IS_PRIMARY_PAF			(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_IN_PAF				(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_OUT_PAF			(1)
#define IA_CSS_ISA_NEEDS_SLICED_IN_PAF				(0)
#define IA_CSS_ISA_NEEDS_SLICED_OUT_PAF				(0)

/* ==================== DPC_PEXT specific properties ==================== */
#define IA_CSS_ISA_KERNEL_IS_PRIMARY_DPC_PEXT		(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_IN_DPC_PEXT		(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_OUT_DPC_PEXT		(0)
#define IA_CSS_ISA_NEEDS_SLICED_IN_DPC_PEXT			(0)
#define IA_CSS_ISA_NEEDS_SLICED_OUT_DPC_PEXT		(0)

/* ========== PIFCONV_OUTPUT_NONSCALED specific properties ================= */
#define IA_CSS_ISA_KERNEL_IS_PRIMARY_PIFCONV_OUTPUT_NONSCALED		(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_IN_PIFCONV_OUTPUT_NONSCALED		(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_OUT_PIFCONV_OUTPUT_NONSCALED		(0)
#define IA_CSS_ISA_NEEDS_SLICED_IN_PIFCONV_OUTPUT_NONSCALED		(0)
#define IA_CSS_ISA_NEEDS_SLICED_OUT_PIFCONV_OUTPUT_NONSCALED		(0)

/* ========== PIFCONV_OUTPUT_SCALED specific properties ================= */
#define IA_CSS_ISA_KERNEL_IS_PRIMARY_PIFCONV_OUTPUT_SCALED		(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_IN_PIFCONV_OUTPUT_SCALED		(0)
#define IA_CSS_ISA_NEEDS_SPATIAL_OUT_PIFCONV_OUTPUT_SCALED		(0)
#define IA_CSS_ISA_NEEDS_SLICED_IN_PIFCONV_OUTPUT_SCALED		(0)
#define IA_CSS_ISA_NEEDS_SLICED_OUT_PIFCONV_OUTPUT_SCALED		(0)

/* ==================== 3A_STAT_AWB specs - START ==================== */
/* in addition to register bank, it has a 0xB40 memory bank to store output, found in reg_descr.hsd */
#define IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AWB_SECTION_COUNT					(1)
#define IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AWB_MAX_SIZE_SECTION_0					(0x28)
#define IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AWB_DEST_OFFSET_SECTION_0				(0xB4C)
/* TODO: gen_ctrl register at 0xB74 is not used, why? */

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_SECTION_COUNT					(0)

/* Spatial Parameter Terminal In does not exist for 3A_STAT_AWB */

#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_SECTION_COUNT				(2)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_COMPUTE_UNITS_PER_ELEM			(1)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MAX_COMPUTE_UNITS_PER_SLICE		(160)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH		(16)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH		(80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT		(16)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT		(60)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MAX_SLICE_SIZE_SECTION_0			(0x500)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_ELEM_SIZE_SECTION_0			(0x8)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_SLICE_0_DEST_OFFSET_SECTION_0		(0x0)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_NEXT_SLICE_OFFSET_SECTION_0		(0x500)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_MAX_SLICE_SIZE_SECTION_1			(0xA0)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_ELEM_SIZE_SECTION_1			(0x1)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_SLICE_0_DEST_OFFSET_SECTION_1		(0xA00)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_NEXT_SLICE_OFFSET_SECTION_1		(0xA0)

/* Sliced Parameter Terminal In does not exist for 3A_STAT_AWB */

/* Sliced Parameter Terminal Out does not exist for 3A_STAT_AWB */

#define IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AWB_SECTION_COUNT						(1)
#define IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AWB_MAX_SIZE_SECTION_0					(0xC)
#define IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AWB_DEST_OFFSET_SECTION_0					(0xB40)
/* ==================== 3A_STAT_AWB specs - END ==================== */

/* ==================== IDS specs - START ==================== */
/* IDS_INTERFACE_VERSION_V1 */
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_SECTION_COUNT						(5)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_0					(0x0C)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_0					(0x00)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_1					(0x10)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_1					(0x14)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_2					(0x18)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_2					(0x50)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_3					(0x20C)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_3					(0x68)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_4					(0x24)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_4					(0x274)

#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_1_SECTION_COUNT						(1)
#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_0						(0x08)
#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_0					(0x0C)

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_VX_1_SECTION_COUNT					(0)

/* IDS LEGACY INTERFACE */
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_SECTION_COUNT						(4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_0						(0x24)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_0					(0x00)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_1						(0x18)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_1					(0x50)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_2						(0x20C)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_2					(0x68)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_3						(0x24)
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_3					(0x274)

#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_SECTION_COUNT						(0)

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_VX_SECTION_COUNT						(0)

/* Spatial Parameter Terminal In does not exist for IDS */

/* Spatial Parameter Terminal Out does not exist for IDS */

/* Sliced Parameter Terminal In does not exist for IDS */

/* Sliced Parameter Terminal Out does not exist for IDS */

/* ==================== IDS specs - END ==================== */


/* ==================== DPC specs used in PSYS - START ==================== */
/* in addition to register bank, it has a 0x3000 memory bank to store LUT, found in reg_descr.hsd */

/*GDDPC_INTERFACE_VERSION_V1 */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_SECTION_COUNT						(4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_0					(0x4)		/* GDC Control */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_0					(0x3378)	/* GDC/DPC Control */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_1					(0x1C0)		/* CfgTable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_1					(0x3000)	/* CfgTable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_2					(0x40)		/* HDR factors */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_2					(0x3488)	/* HDR factors */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_3					(0x4)		/* AF Grid Enable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_3					(0x34C8)	/* AF Grid Enable */

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_VX_1_SECTION_COUNT					(0)

/* Spatial Parameter Terminal In does not exist for DPC */

/* Spatial Parameter Terminal Out does not exist for DPC */

#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_SECTION_COUNT					(2)
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_MAX_SLICE_SIZE_SECTION_0			(0x4)		/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_0			(0x3380)	/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_0			(0x4)		/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_MAX_SLICE_SIZE_SECTION_1			(0x1000)	/* DPC static LUT */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_1			(0x0)		/* DPC static LUT */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_1			(0x1000)	/* DPC static LUT */

#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_SECTION_COUNT					(2)
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_MAX_SLICE_SIZE_SECTION_0			(0x4)		/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_0			(0x34CC)	/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_0			(0x4)		/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_MAX_SLICE_SIZE_SECTION_1			(0x800)		/* AF Pixels metadata */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_1			(0x2000)	/* AF Pixels metadata */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_1			(0x800)		/* AF Pixels metadata */

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_SECTION_COUNT						(3)

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_0						(0x4)
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_0					(0x337C) /* DPC Control */
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_1						(0x1B8)		/* CfgUnitMapping */
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_1					(0x31C0)	/* CfgUnitMapping */

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_2						(0x40)		/* AF pixels grid cfg */
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_2					(0x3388)	/* AF pixels grid cfg */

/* GDDPC LEGACY INTERFACE */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_SECTION_COUNT						(4)

#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_0						(0x8)		/* GDC/DPC Control */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_0					(0x3378)	/* GDC/DPC Control */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_1						(0x1C0)		/* CfgTable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_1					(0x3000)	/* CfgTable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_2						(0x40)		/* HDR factors */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_2					(0x3488)	/* HDR factors */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_3						(0x4)		/* AF Grid Enable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_3					(0x34C8)	/* AF Grid Enable */

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_VX_SECTION_COUNT						(0)

/* Spatial Parameter Terminal In does not exist for DPC */

/* Spatial Parameter Terminal Out does not exist for DPC */

#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_SECTION_COUNT					(2)
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_MAX_SLICE_SIZE_SECTION_0				(0x4)		/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_0			(0x3380)	/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_NEXT_SLICE_OFFSET_SECTION_0			(0x4)		/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_MAX_SLICE_SIZE_SECTION_1				(0x1000)	/* DPC static LUT */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_1			(0x0)		/* DPC static LUT */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_NEXT_SLICE_OFFSET_SECTION_1			(0x1000)	/* DPC static LUT */

#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_SECTION_COUNT					(2)
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_MAX_SLICE_SIZE_SECTION_0			(0x4)		/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_0			(0x34CC)	/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_NEXT_SLICE_OFFSET_SECTION_0			(0x4)		/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_MAX_SLICE_SIZE_SECTION_1			(0x800)		/* AF Pixels metadata */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_1			(0x2000)	/* AF Pixels metadata */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_NEXT_SLICE_OFFSET_SECTION_1			(0x800)		/* AF Pixels metadata */

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_SECTION_COUNT						(2)
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_MAX_SIZE_SECTION_0						(0x1B8)		/* CfgUnitMapping */
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_0					(0x31C0)	/* CfgUnitMapping */
/* PSYS uses GDC version v1*/
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_MAX_SIZE_SECTION_1						(0x40)		/* AF pixels grid cfg */

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_1					(0x3388)	/* AF pixels grid cfg */
/* ==================== DPC specs - END ==================== */



/* ==================== DPC_V2 specs used in ISYS - START ==================== */
/* in addition to register bank, it has a 0x3000 memory bank to store LUT, found in reg_descr.hsd */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_SECTION_COUNT						(4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_MAX_SIZE_SECTION_0						(0x8)		/* GDC/DPC Control */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_DEST_OFFSET_SECTION_0					(0x3378)	/* GDC/DPC Control */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_MAX_SIZE_SECTION_1						(0x1C0)		/* CfgTable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_DEST_OFFSET_SECTION_1					(0x3000)	/* CfgTable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_MAX_SIZE_SECTION_2						(0x40)		/* HDR factors */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_DEST_OFFSET_SECTION_2					(0x3488)	/* HDR factors */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_MAX_SIZE_SECTION_3						(0x4)		/* AF Grid Enable */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_DEST_OFFSET_SECTION_3					(0x34C8)	/* AF Grid Enable */

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_V2_SECTION_COUNT						(0)

/* Spatial Parameter Terminal In does not exist for DPC */

/* Spatial Parameter Terminal Out does not exist for DPC */

#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_SECTION_COUNT					(2)
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_MAX_SLICE_SIZE_SECTION_0				(0x4)		/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_SLICE_0_DEST_OFFSET_SECTION_0			(0x3380)	/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_NEXT_SLICE_OFFSET_SECTION_0			(0x4)		/* DPC static LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_MAX_SLICE_SIZE_SECTION_1				(0x1000)	/* DPC static LUT */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_SLICE_0_DEST_OFFSET_SECTION_1			(0x0)		/* DPC static LUT */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_V2_NEXT_SLICE_OFFSET_SECTION_1			(0x1000)	/* DPC static LUT */

#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_SECTION_COUNT					(2)
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_MAX_SLICE_SIZE_SECTION_0			(0x4)		/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_SLICE_0_DEST_OFFSET_SECTION_0			(0x34CC)	/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_NEXT_SLICE_OFFSET_SECTION_0			(0x4)		/* AF LUT limit */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_MAX_SLICE_SIZE_SECTION_1			(0x800)		/* AF Pixels metadata */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_SLICE_0_DEST_OFFSET_SECTION_1			(0x2000)	/* AF Pixels metadata */
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_V2_NEXT_SLICE_OFFSET_SECTION_1			(0x800)		/* AF Pixels metadata */

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_SECTION_COUNT						(2)
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_MAX_SIZE_SECTION_0						(0x1B8)		/* CfgUnitMapping */
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_DEST_OFFSET_SECTION_0					(0x31C0)	/* CfgUnitMapping */


/* ISYS uses GDC version v2*/
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_MAX_SIZE_SECTION_1						(0x100)		/* AF pixels grid cfg */

#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_DEST_OFFSET_SECTION_1					(0x3388)	/* AF pixels grid cfg */
/* ==================== DPC specs - END ==================== */

/* ==================== DPC_PEXT specs - START ==================== */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_SECTION_COUNT						(2)
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_MAX_SIZE_SECTION_0					(0x8)
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_DEST_OFFSET_SECTION_0					(0x0)
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_MAX_SIZE_SECTION_1					(0x8)
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_DEST_OFFSET_SECTION_1					(0xC)

#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_PEXT_SECTION_COUNT					(0)
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_PEXT_SECTION_COUNT						(0)
/* ==================== DPC_PEXT specs - END ==================== */

/* ==================== PAF specs - START ==================== */
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_SECTION_COUNT							(3)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_MAX_SIZE_SECTION_0						(0x18)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_DEST_OFFSET_SECTION_0						(0x0)

/* This is an PAF ACB configuration an not really the configuration on PAF FF. Hence giving - offsets*/
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_MAX_SIZE_SECTION_1						(0x4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_DEST_OFFSET_SECTION_1						(-0x20)

/* PAF PWR_FEATURE register re-used to support OV pattern */
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_MAX_SIZE_SECTION_2						(0x4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PAF_DEST_OFFSET_SECTION_2						(0x18)

#define	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_PAF_SECTION_COUNT						(0)
/* Number of PAF blocks = 12*16 PAF blocks
 * Max number of phase steps in each block: 11 steps (0-10)
 * 	for step 10, only the LSB values are valid and MSB 2bytes are reserved
 * 	Hence for each block height, we will have to read in 12 steps
 * Size of each phase value =  2 bytes
 * Total size required for PAF output = 2bytes * 12*16 blocks *12 steps
 * */

/* Spatial Parameter Terminal In does not exist for PAF*/

/* Spatial Parameter Terminal Out for PAF*/
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_PAF_SECTION_COUNT					(1)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_PAF_COMPUTE_UNITS_PER_ELEM				(1)	/**/

#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_PAF_MAX_SLICE_SIZE_SECTION_0				(0x1200) /*12*16 #PAF blocks# * 2bytes*12 #Phase output size per block#*/
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_PAF_ELEM_SIZE_SECTION_0				(0x18)	/*Size of each phase output in a grid*/
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_PAF_SLICE_0_DEST_OFFSET_SECTION_0			(0x44)	/*FF register offset from kernel base*/
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_OUT_PAF_NEXT_SLICE_OFFSET_SECTION_0			(0x180)	/*Determines the next FF location*/


/* Sliced Parameter Terminal In does not exist for PAF*/

/* Sliced Parameter Terminal Out does not exist for PAF*/

#define IA_CSS_ISA_PROGRAM_TERMINAL_PAF_SECTION_COUNT							(0)
/* ==================== PAF specs - END ==================== */

/* ============== LSC Spatial-in terminal properties ============= */
/* Sensor Type-0 */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SECTION_COUNT			(4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_COMPUTE_UNITS_PER_ELEM		(8)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_COMPUTE_UNITS_PER_SLICE		(128)	/* HW limit for slice height calculation */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH	(8)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH	(64)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT	(8)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT	(64)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_0		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_0			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_0	(0x0)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_0		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_1		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_1			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_1	(0x300)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_1		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_2		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_2			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_2	(0x600)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_2		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_3		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_3			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_3	(0x900)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_3		(0x100)

/* Sensor Type-1 */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SECTION_COUNT			(4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_COMPUTE_UNITS_PER_ELEM		(2)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_COMPUTE_UNITS_PER_SLICE		(128)	/* HW limit for slice height calculation */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH	(8)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH	(64)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT	(8)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT	(64)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_0		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_0			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_0	(0x0)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_0		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_1		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_1			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_1	(0x300)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_1		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_2		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_2			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_2	(0x600)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_2		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_3		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_3			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_3	(0x900)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_3		(0x100)

/* Sensor Type-2 */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SECTION_COUNT			(8)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_COMPUTE_UNITS_PER_ELEM		(1)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_COMPUTE_UNITS_PER_SLICE		(32)	/* HW limit for slice height calculation */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH	(8)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH	(32)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT	(8)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT	(32)	/* HW limit for checking only */
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_0		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_0			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_0	(0x0)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_0		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_1		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_1			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_1	(0x300)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_1		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_2		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_2			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_2	(0x600)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_2		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_3		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_3			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_3	(0x900)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_3		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_4		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_4			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_4	(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_4		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_5		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_5			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_5	(0x380)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_5		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_6		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_6			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_6	(0x680)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_6		(0x100)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_7		(0x80)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_7			(0x4)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_7	(0x980)
#define IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_7		(0x100)
/* =============================================================== */

#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_MAX_SLICE_SIZE_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_SLICE_0_DEST_OFFSET_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_NEXT_SLICE_OFFSET_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_MAX_SLICE_SIZE_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_SLICE_0_DEST_OFFSET_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_NEXT_SLICE_OFFSET_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_2 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_2
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_3 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_3
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_4 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_4
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_4 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_4
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_4 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_4
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_4 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_4
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_5 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_5
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_5 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_5
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_5 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_5
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_5 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_5
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_6 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_6
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_6 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_6
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_6 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_6
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_6 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_6
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_7 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_MAX_SLICE_SIZE_SECTION_7
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_7 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_7
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_7 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_SLICE_0_DEST_OFFSET_SECTION_7
#define IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_7 IA_CSS_ISA_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_NEXT_SLICE_OFFSET_SECTION_7

#ifdef IDS_INTERFACE_VERSION_V1
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_SECTION_COUNT				IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_SECTION_COUNT
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_0			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_0			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_1			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_1			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_2			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_2			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_3			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_3			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_4			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_4
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_4			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_4
#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_SECTION_COUNT			IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_VX_1_SECTION_COUNT
#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_SECTION_COUNT				IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_1_SECTION_COUNT
#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_MAX_SIZE_SECTION_0			IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_1_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_DEST_OFFSET_SECTION_0			IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_1_DEST_OFFSET_SECTION_0
#else /* IDS_INTERFACE_VERSION_V1 */
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_SECTION_COUNT				IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_SECTION_COUNT
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_0			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_0			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_1			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_1			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_2			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_2			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_3			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_MAX_SIZE_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_3			IA_CSS_ISA_PARAMETER_TERMINAL_IDS_VX_DEST_OFFSET_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_SECTION_COUNT			IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_VX_SECTION_COUNT
#define IA_CSS_ISA_PROGRAM_TERMINAL_IDS_SECTION_COUNT				IA_CSS_ISA_PROGRAM_TERMINAL_IDS_VX_SECTION_COUNT
#endif /* IDS_INTERFACE_VERSION_V1 */

#ifdef GDDPC_INTERFACE_VERSION_V1
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_SECTION_COUNT					IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_SECTION_COUNT
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_0				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_0				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_1				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_1				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_2				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_2				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_3				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_3				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT				IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_VX_1_SECTION_COUNT
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SECTION_COUNT			IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_SECTION_COUNT
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_0		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_0	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_0		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_1		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_1	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_1		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT			IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_SECTION_COUNT
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_0		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_0	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_0	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_1		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_1	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_1	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_1_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_SECTION_COUNT					IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_SECTION_COUNT
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_0				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_0				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_1				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_1
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_1				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_2				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_MAX_SIZE_SECTION_2
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_2				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_1_DEST_OFFSET_SECTION_2
#else /* GDDPC_INTERFACE_VERSION_V1 */
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_SECTION_COUNT					IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_SECTION_COUNT
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_0				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_0				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_1				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_1				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_2				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_2				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_2
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_3				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_MAX_SIZE_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_3				IA_CSS_ISA_PARAMETER_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_3
#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT				IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_VX_SECTION_COUNT
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SECTION_COUNT			IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_SECTION_COUNT
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_0		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_0	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_0		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_1		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_1	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_1		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_VX_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT			IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_SECTION_COUNT
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_0		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_0	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_0	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_1		IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_1	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_1	IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_VX_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_SECTION_COUNT					IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_SECTION_COUNT
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_0				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_MAX_SIZE_SECTION_0
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_0				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_0
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_1				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_MAX_SIZE_SECTION_1
#define IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_1				IA_CSS_ISA_PROGRAM_TERMINAL_DPC_VX_DEST_OFFSET_SECTION_1
#endif /* GDDPC_INTERFACE_VERSION_V1 */

/* ==================== PIFCONV_OUTPUT_NONSCALED specs - START ==================== */
#define IA_CSS_ISA_PARAMETER_TERMINAL_PIFCONV_OUTPUT_NONSCALED_SECTION_COUNT		(1)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PIFCONV_OUTPUT_NONSCALED_MAX_SIZE_SECTION_0	(0x4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PIFCONV_OUTPUT_NONSCALED_DEST_OFFSET_SECTION_0	(0x0)
#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_PIFCONV_OUTPUT_NONSCALED_SECTION_COUNT	(0)

#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_NONSCALED_SECTION_COUNT		(2)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_NONSCALED_MAX_SIZE_SECTION_0		(0x8)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_NONSCALED_DEST_OFFSET_SECTION_0	(0x4)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_NONSCALED_MAX_SIZE_SECTION_1		(0x4)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_NONSCALED_DEST_OFFSET_SECTION_1	(0x0) /* 0 because this register is in GPreg, NOT in Pifconv device. */
/* ==================== PIFCONV_OUTPUT_NONSCALED specs - END ==================== */

/* ==================== PIFCONV_OUTPUT_SCALED specs - START ==================== */
#define IA_CSS_ISA_PARAMETER_TERMINAL_PIFCONV_OUTPUT_SCALED_SECTION_COUNT		(1)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PIFCONV_OUTPUT_SCALED_MAX_SIZE_SECTION_0		(0x4)
#define IA_CSS_ISA_PARAMETER_TERMINAL_PIFCONV_OUTPUT_SCALED_DEST_OFFSET_SECTION_0	(0x0)
#define IA_CSS_ISA_PARAMETER_TERMINAL_OUT_PIFCONV_OUTPUT_SCALED_SECTION_COUNT		(0)

#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_SCALED_SECTION_COUNT			(2)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_SCALED_MAX_SIZE_SECTION_0		(0x8)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_SCALED_DEST_OFFSET_SECTION_0		(0x4)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_SCALED_MAX_SIZE_SECTION_1		(0x4)
#define IA_CSS_ISA_PROGRAM_TERMINAL_PIFCONV_OUTPUT_SCALED_DEST_OFFSET_SECTION_1		(0x0) /* 0 because this register is in GPreg, NOT in Pifconv device. */
/* ==================== PIFCONV_OUTPUT_SCALED specs - END ==================== */

/* TODO: REMOVE BACKWARD COMPATIBILITY */
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_SECTION_COUNT IA_CSS_ISA_PARAMETER_TERMINAL_IDS_SECTION_COUNT
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_0 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_0
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_0 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_0
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_1 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_1
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_1 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_2 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_2
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_2 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_2
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_3 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_MAX_SIZE_SECTION_3
#define IA_CSS_ISYS_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_3 IA_CSS_ISA_PARAMETER_TERMINAL_IDS_DEST_OFFSET_SECTION_3
#define IA_CSS_ISYS_PARAMETER_TERMINAL_OUT_IDS_SECTION_COUNT IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_SECTION_COUNT
#define IA_CSS_ISYS_PROGRAM_TERMINAL_IDS_SECTION_COUNT IA_CSS_ISA_PROGRAM_TERMINAL_IDS_SECTION_COUNT
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_SECTION_COUNT IA_CSS_ISA_PARAMETER_TERMINAL_DPC_SECTION_COUNT
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_0 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_0
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_0 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_0
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_1 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_1
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_1 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_2 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_2
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_2 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_2
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_3 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_MAX_SIZE_SECTION_3
#define IA_CSS_ISYS_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_3 IA_CSS_ISA_PARAMETER_TERMINAL_DPC_DEST_OFFSET_SECTION_3
#define IA_CSS_ISYS_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_SECTION_COUNT IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SECTION_COUNT
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_0 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_1 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_IN_DPC_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SECTION_COUNT
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_0 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_1 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_ISYS_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_ISA_SLICED_PARAMETER_TERMINAL_OUT_DPC_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_ISYS_PROGRAM_TERMINAL_DPC_SECTION_COUNT IA_CSS_ISA_PROGRAM_TERMINAL_DPC_SECTION_COUNT
#define IA_CSS_ISYS_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_0 IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_0
#define IA_CSS_ISYS_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_0 IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_0
#define IA_CSS_ISYS_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_1 IA_CSS_ISA_PROGRAM_TERMINAL_DPC_MAX_SIZE_SECTION_1
#define IA_CSS_ISYS_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_1 IA_CSS_ISA_PROGRAM_TERMINAL_DPC_DEST_OFFSET_SECTION_1
/* END OF TODO */

#endif /* __IA_CSS_ISA_PARAMETER_DEFS_DEP_H */

