/*
 * Copyright (C) 2015 - 2018 Intel Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __IA_CSS_ISYS_PARAMETER_DEFS_DEP_H
#define __IA_CSS_ISYS_PARAMETER_DEFS_DEP_H

#include "ia_css_isa_parameter_defs.h"


/* For ISYS, ISA is the only service that can be placed in the ISYS program group.
 * Therefore, ISA kernel ids and acc ids can be named as ISYS
 */
enum ia_css_isys_kernel_id {
	IA_CSS_ISYS_KERNEL_ID_INL = 0,
	IA_CSS_ISYS_KERNEL_ID_BLC_GLOBAL,
	IA_CSS_ISYS_KERNEL_ID_BLC_SENSOR_TYPE_0,
	IA_CSS_ISYS_KERNEL_ID_BLC_SENSOR_TYPE_1,
	IA_CSS_ISYS_KERNEL_ID_BLC_SENSOR_TYPE_2,
	IA_CSS_ISYS_KERNEL_ID_PCLN,
	IA_CSS_ISYS_KERNEL_ID_LSC_SENSOR_TYPE_0,
	IA_CSS_ISYS_KERNEL_ID_LSC_SENSOR_TYPE_1,
	IA_CSS_ISYS_KERNEL_ID_LSC_SENSOR_TYPE_2,
	/*ISYS uses IA_CSS_ISYS_KERNEL_ID_DPC_V2
	  PSYS uses IA_CSS_ISYS_KERNEL_ID_DPC_V1
	  Since at in either ISYS/PSYS only one DPC is present
	  sharing the kernel IDs
	 */
	IA_CSS_ISYS_KERNEL_ID_DPC,
	IA_CSS_ISYS_KERNEL_ID_IDS,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AWB,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AF,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AE_CCM,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AE,
#ifndef ISA_GEN_TERMINAL
	IA_CSS_ISYS_KERNEL_ID_PAF,
	IA_CSS_ISYS_KERNEL_ID_DPC_PEXT,
#endif /* ISA_GEN_TERMINAL */
	N_IA_CSS_ISYS_KERNEL_ID
};

enum ia_css_isys_acc_id {
	IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION = 0,
	IA_CSS_ISYS_ACC_ID_LSC,
	IA_CSS_ISYS_ACC_ID_GDDPC,
	IA_CSS_ISYS_ACC_ID_INPUT_DOWNSCALER,
	IA_CSS_ISYS_ACC_ID_AWB_STAT,
	IA_CSS_ISYS_ACC_ID_AF_STAT,
	IA_CSS_ISYS_ACC_ID_AE_STAT,
#ifndef ISA_GEN_TERMINAL
	IA_CSS_ISYS_ACC_ID_PAF,
#endif /* ISA_GEN_TERMINAL */
	N_IA_CSS_ISYS_ACC_ID
};

#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_INL			(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_GLOBAL		(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_SENSOR_TYPE_0	(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_SENSOR_TYPE_1	(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_SENSOR_TYPE_2	(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_PCLN			(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_LSC_SENSOR_TYPE_0	(IA_CSS_ISYS_ACC_ID_LSC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_LSC_SENSOR_TYPE_1	(IA_CSS_ISYS_ACC_ID_LSC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_LSC_SENSOR_TYPE_2	(IA_CSS_ISYS_ACC_ID_LSC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_DPC_V2		(IA_CSS_ISYS_ACC_ID_GDDPC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_IDS			(IA_CSS_ISYS_ACC_ID_INPUT_DOWNSCALER)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AWB		(IA_CSS_ISYS_ACC_ID_AWB_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AF		(IA_CSS_ISYS_ACC_ID_AF_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AE_CCM	(IA_CSS_ISYS_ACC_ID_AE_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AE		(IA_CSS_ISYS_ACC_ID_AE_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_PAF			(IA_CSS_ISYS_ACC_ID_PAF)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_DPC_PEXT		(IA_CSS_ISYS_ACC_ID_GDDPC)

/* The following define the section count for the param_in/out and program terminals */
/* If used by PAL/P2P and FW we ensure compatibility at section count */
#define IA_CSS_ISYS_PARAMETER_TERMINAL_SECTION_COUNT	(				\
	IA_CSS_ISA_PARAMETER_TERMINAL_INL_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_GLOBAL_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_PCLN_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_LSC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_LSC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_LSC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_IDS_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AWB_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AF_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AE_CCM_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AE_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_PAF_SECTION_COUNT)


#define IA_CSS_ISYS_PARAMETER_TERMINAL_OUT_SECTION_COUNT	(			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_INL_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_GLOBAL_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_PCLN_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_LSC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_LSC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_LSC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_V2_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AF_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AE_CCM_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AE_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_PEXT_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_PAF_SECTION_COUNT)


#define IA_CSS_ISYS_PROGRAM_TERMINAL_SECTION_COUNT	(				\
	IA_CSS_ISA_PROGRAM_TERMINAL_INL_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_GLOBAL_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_SENSOR_TYPE_0_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_SENSOR_TYPE_1_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_SENSOR_TYPE_2_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_PCLN_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_LSC_SENSOR_TYPE_0_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_LSC_SENSOR_TYPE_1_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_LSC_SENSOR_TYPE_2_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_IDS_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AWB_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AF_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AE_CCM_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AE_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_DPC_PEXT_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_PAF_SECTION_COUNT)

#define LSC_TYPE_0_SECTION_ELEMENT_SIZES_INITIALIZER																\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_0, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_1,	\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_2, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_3

#define LSC_TYPE_1_SECTION_ELEMENT_SIZES_INITIALIZER																\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_0, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_1,	\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_2, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_3

#define LSC_TYPE_2_SECTION_ELEMENT_SIZES_INITIALIZER																\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_0, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_1,	\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_2, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_3,	\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_4, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_5,	\
	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_6, IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_7

#endif /* __IA_CSS_ISYS_PARAMETER_DEFS_DEP_H */
